### ISSUE TITLE
Expression does not plot: (1-(x/6)*(1-(x/20)))

### ISSUE THREAD

**Issue by michalkonecny** [michalkonecny/robust-plots#63]
## Details:
Hours Spent: 2

## Background
Some expressions lead to a blank plot:
![image](https://user-images.githubusercontent.com/1597935/85184578-27211f80-b288-11ea-8886-a708e59b4a38.png)

## Overview
On inputting the expression (1-(x/6)*(1-(x/20))) the plot is entirely empty.
Various minor simplifications of this expression do plot as expected, eg
 ((x/6)*(1-(x/20))) and  (1-(x)*(1-(x/20))).

## Acceptance Criteria
- [x]  Inputting the expression (1-(x/6)*(1-(x/20))) gives a plot similar to:
![image](https://user-images.githubusercontent.com/1597935/85184422-aeba5e80-b287-11ea-921c-c8bf133d30c2.png)

## Closing Notes

Overview of changes can be found in PR #72

The bug was caused by the fact that the list of extracted variables was not passed down to the next recursive call of `orderDepencenciesWithMap`. This was amended by simply appending the `extracted` and `newExtractedValueArray` together.

![image](https://user-images.githubusercontent.com/24320350/85928622-42061c00-b8a6-11ea-89fb-37e90c50eb20.png)
The plot appears as expected.

**Comment by RelativeForce** [comment]
For this expression `(1-(x/6)(1-(x/20)))` is the correct tree is `(1 - (x / 6)) * (1 - (x / 20))` or `1 - ((x / 6) * (1 - (x / 20)))` ? The reason I ask is because if the correct tree is the former then the plot appears correctly. I think we may be having an issue with operator precedence.

![image](https://user-images.githubusercontent.com/24320350/85839326-b354aa80-b792-11ea-8f83-bf1bb1ccedb3.png)
Screenshot from #71 build

**Comment by michalkonecny** [comment]
The expression `1-(x/6)*(1-(x/20))` should be parsed as `1 - ((x / 6) * (1 - (x / 20)))` since `*` binds more tightly than `-`.
